config/routes.rb
Rails.application.routes.draw do
  # get "/products/montage" => "products#montage", as: "products_montage"
  root to: 'products#index'
  resources :products do
    collection { post :upload }
  end
  # Sidekiq Web UI
  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :first_image, :last_image,
  :presence => true,
  :uniqueness => true,
  :format => {
    :with => URI::regexp(%w(http https)),
    :message => 'must be a valid URL'
  }
  validates :first_image, :last_image, :format => {
    :with => /\.(png|jpg|jpeg)\Z/i,
    :message => 'must be an image'
  }
  def self.import(file)
    counter = 0
    message = []
    CSV.foreach(file.path) do |row|
      product = Product.assign_from_row(row)
      if product.new_record? & product.save
        MontageWorker.perform_async(product.id)
        counter += 1
      else
        message << product.errors.full_messages
      end
    end
    return counter, message
  end

  def self.assign_from_row(row)
    product = Product.where(first_image: row[0]).where(last_image: row[1]).first_or_initialize
    product
  end

  def self.to_csv(headers = column_names, options = {})
    CSV.generate(headers: true) do |csv|
      csv << headers

      all.each do |product|
        csv << headers.map { |attr| product.send(attr)}
      end
    end
  end

  def montage_image
    super || "N/A"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv(['id', 'first_image', 'last_image', 'montage_image']), filename: "product_images-#{DateTime.now.strftime('%Y-%m-%d-%H-%M-%S')}.csv" }
    end
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def montage
    MontageWorker.perform_async(Time.now, Time.now + 1)
    render plain: "request to perform montage added to the queue"
  end

  def upload
    begin
      result = Product.import(params[:file])
      redirect_to products_url, warning: "#{result[0]} #{"image".pluralize(result[0])} imported. #{result[1].flatten.uniq.join(", ")}"
    rescue
      redirect_to products_url, danger: "Invalid or Missing CSV file."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:first_image, :last_image, :montage_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoMontageTool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main role='main'>
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
      <% end %>
      <div class='container'>
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_image %>
    <%= form.text_field :first_image %>
  </div>

  <div class="field">
    <%= form.label :last_image %>
    <%= form.text_field :last_image %>
  </div>

  <div class="field">
    <%= form.label :montage_image %>
    <%= form.text_field :montage_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_montage.html.erb
<div id="wrapper">

  <h1>Generate a montage</h1>

  <button class="generate-images-montage">
    montage call-to-action
  </button>

  <div id="footer-javascripts">
    <script type="text/javascript">
      var button = document.querySelector("button.generate-images-montage");
      button.addEventListener("click", function() {
        window.location = "<%= products_montage_url %>"
      });
    </script>
  </div>

</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="table-responsive">
  <table class='table table-bordered table-striped'>
    <thead>
        <th>ID</th>
        <th>First image</th>
        <th>Last image</th>
        <th>Montage image</th>
    </thead>
    <tbody style="font-size: 12px; white-space: nowrap">
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.first_image %></td>
          <td><%= product.last_image %></td>
          <td><%= product.montage_image %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= form_tag upload_products_path, multipart: true, class: 'form-inline' do %>
  <div class="form-group pull-right">
    <%= link_to "Export", products_path(format: "csv"), class: 'btn btn-primary' %>
  </div>

  <div class="form-group">
    <%= submit_tag "Upload", class: 'btn btn-info' %>
    <br>
    <%= file_field_tag :file, class: '' %>
  </div>
<% end %>

<%= link_to 'Background Processing Dashboard', sidekiq_web_path, class: 'btn btn-warning pull-right', target: :_blank %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First image:</strong>
  <%= @product.first_image %>
</p>

<p>
  <strong>Last image:</strong>
  <%= @product.last_image %>
</p>

<p>
  <strong>Montage image:</strong>
  <%= @product.montage_image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>